version: '3'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: realworld-docker-frontend
    command: npm run start
    restart: unless-stopped
    environment:
      CHOKIDAR_USEPOLLING: true
    stdin_open: true
    tty: true
    volumes:
      - /usr/src/app/build
      - /usr/src/app/node_modules
      - ./frontend:/usr/src/app
    networks:
      - realworld-docker-network
  api:
    build: ./api
    container_name: realworld-docker-api
    command: npm run dev
    restart: unless-stopped
    environment:
      PORT: 3001
      MONGO_URL: mongodb://api_db:27017/api
      AUTH_API_URL: http://auth:3002/api
    depends_on:
      - api_db
    volumes:
      - /usr/src/app/node_modules
      - ./api:/usr/src/app
    networks:
      - realworld-docker-network
  auth:
    build: ./auth
    container_name: realworld-docker-auth
    command: npm run start
    restart: unless-stopped
    environment:
      PORT: 3002
      MONGO_URL: mongodb://auth_db:27017/auth
      API_URL: htpp://api:3001/api
    depends_on:
      - auth_db
    volumes:
      - /usr/src/app/node_modules
      - ./auth:/usr/src/app
    networks:
      - realworld-docker-network
  api_db:
    image: mongo:latest
    container_name: realworld-docker-api-db
    volumes:
      - mongodb_api:/data/db
    networks:
      - realworld-docker-network
  auth_db:
    image: mongo:latest
    container_name: realworld-docker-auth-db
    volumes:
      - mongodb_auth:/data/db
    networks:
      - realworld-docker-network
  nginx:
    image: nginx:1.26.3
    container_name: realworld-docker-nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - api
      - auth
    volumes:
      - ./nginx/nginx.conf.dev:/etc/nginx/conf.d/nginx.conf
    networks:
      - realworld-docker-network
volumes:
  mongodb_api:
  mongodb_auth:
networks:
  realworld-docker-network:
    driver: bridge