version: '3'

services:
  api:
    build: ./api
    command: npm run dev
    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
      PORT: 3000
      HOST: http://realworld-docker.com
      MONGO_URL: mongodb://api_db:27017/api
    depends_on:
      - api_db
    volumes:
      - /usr/src/app/node_modules
      - ./api:/usr/src/app
  api_db:
    image: mongo:latest
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data: