version: '3'

services:
  frontend:
    build: ./frontend
    container_name: realworld-docker-frontend
    command: serve -s build -l 3000
    restart: unless-stopped
    environment:
      CHOKIDAR_USEPOLLING: true
    stdin_open: true
    tty: true
    volumes:
      - /usr/src/app/node_modules
      - ./frontend:/usr/src/app
  api:
    build: ./api
    container_name: realworld-docker-api
    command: npm run start
    restart: unless-stopped
    ports:
      - '3001:3001'
    environment:
      PORT: 3001
      HOST: http://realworld-docker.com
      MONGO_URL: mongodb://api_db:27017/api
    depends_on:
      - api_db
    volumes:
      - /usr/src/app/node_modules
      - ./api:/usr/src/app
  auth:
    build: ./auth
    container_name: realworld-docker-auth
    command: npm run start
    restart: unless-stopped
    ports:
      - '3002:3002'
    environment:
      PORT: 3002
      HOST: http://realworld-docker.com
      MONGO_URL: mongodb://auth_db:27017/auth
    depends_on:
      - auth_db
    volumes:
      - /usr/src/app/node_modules
      - ./auth:/usr/src/app
  api_db:
    image: mongo:latest
    container_name: realworld-docker-api-db
    volumes:
      - mongodb_api:/data/db
  auth_db:
    image: mongo:latest
    container_name: realworld-docker-auth-db
    volumes:
      - mongodb_auth:/data/db
  nginx:
    image: nginx:1.26.3
    container_name: realworld-docker-nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
    volumes:
      - ./nginx/nginx.conf.prod:/etc/nginx/conf.d/nginx.conf
volumes:
  mongodb_api:
  mongodb_auth: